/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: /etc/confd/tailf-acm.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _TACM_
#define _TACM_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef tacm__ns
#define tacm__ns 1103336897
#define tacm__ns_id "http://tail-f.com/yang/acm"
#define tacm__ns_uri "http://tail-f.com/yang/acm"
#endif

#define tacm_name 1998270519
#define tacm_command 36215204
#define tacm_log_if_default_permit 977181334
#define tacm_action 571883887
#define tacm_gid 1021704153
#define tacm_access_operations 1622834780
#define tacm_cmdrule 367587804
#define tacm_log_if_permit 825727182
#define tacm_context 1600175075
#define tacm_cmd_read_default 1843143316
#define tacm_comment 452863039
#define tacm_cmd_exec_default 311962167

#ifdef __cplusplus
}
#endif

#endif

