#CONFIG_DEV_BROADCOM_ESDK_WLAN=y
#CONFIG_ACTIVEDEV_GITUSERNAME="git"
#CONFIG_ACTIVEDEV_GITROOTPATH="sw-stash.freescale.net/sslab"
#CONFIG_DEV_BROADCOM_ESDK_WLAN_GITTREE="wifi-broadcom-rv340w.git"
#CONFIG_DEV_BROADCOM_ESDK_WLAN_GITBRANCH="release/5_0_9_1"
